// config/config.js
const path = require('path');

module.exports = {
  PORT: process.env.PORT || 3000,
  UPLOAD_DIR: path.join(__dirname, '../uploads/'),
  UPLOAD_DIRC: path.join(__dirname, '../uploads/chouffeur/'),
  MAX_FILE_SIZE: 10 * 1024 * 1024, // 10MB
  ALLOWED_TYPES: {
    'image/jpeg': ['.jpg', '.jpeg'],
    'image/png': ['.png'],
    'image/gif': ['.gif'],
  },
  ALLOWED_TYPES: {
    'image/jpeg': ['.jpg', '.jpeg'],
    'image/png': ['.png'],
    'image/gif': ['.gif'],
    'image/heic': ['.heic'], // Optional: Add if you want to support HEIC
  },

    CITIES: {
      
            France: [
              { name: 'Paris', code: 'FR' },
              { name: 'Dijon', code: 'FR' },
              { name: 'Lyon', code: 'FR' },
              { name: 'Marseille', code: 'FR' },
              { name: 'Rennes', code: 'FR' },
              { name: 'Orléans', code: 'FR' },
              { name: 'Bordeaux', code: 'FR' },
              { name: 'Toulouse', code: 'FR' },
              { name: 'Nice', code: 'FR' },
              { name: 'Lille', code: 'FR' },
              { name: 'Strasbourg', code: 'FR' },
              { name: 'Grenoble', code: 'FR' },
              { name: 'Nantes', code: 'FR' },
              { name: 'Brest', code: 'FR' },
              { name: 'Aix-en-Provence', code: 'FR' },
              { name: 'Reims', code: 'FR' },
              { name: 'Toulon', code: 'FR' },
              { name: 'Montpellier', code: 'FR' },
              { name: 'Le Havre', code: 'FR' },
              { name: 'Clermont-Ferrand', code: 'FR' },
              { name: 'Perpignan', code: 'FR' },
              { name: 'Caen', code: 'FR' },
              { name: 'Rouen', code: 'FR' },
              { name: 'Nancy', code: 'FR' },
              { name: 'Angers', code: 'FR' },
              { name: 'Poitiers', code: 'FR' },
              { name: 'Limoges', code: 'FR' },
              { name: 'Metz', code: 'FR' },
              { name: 'Mulhouse', code: 'FR' },
              { name: 'Besançon', code: 'FR' },
              { name: 'Valence', code: 'FR' },
              { name: 'Versailles', code: 'FR' },
              { name: 'Chartres', code: 'FR' },
              { name: 'Cannes', code: 'FR' },
              { name: 'Antibes', code: 'FR' },
              { name: 'Arles', code: 'FR' },
              { name: 'Pau', code: 'FR' },
              { name: 'Dunkerque', code: 'FR' },
              { name: 'Calais', code: 'FR' },
              { name: 'Colmar', code: 'FR' },
              { name: 'Nîmes', code: 'FR' },
              { name: 'Troyes', code: 'FR' },
              { name: 'Châlons-en-Champagne', code: 'FR' },
              { name: 'Biarritz', code: 'FR' },
              { name: 'Monaco', code: 'FR' },
              { name: 'Roubaix', code: 'FR' },
              { name: 'Tourcoing', code: 'FR' },
              { name: 'Vannes', code: 'FR' },
              { name: 'Lorient', code: 'FR' },
              { name: 'Chambéry', code: 'FR' },
              { name: 'Bayonne', code: 'FR' },
              { name: 'Grasse', code: 'FR' },
              { name: 'Amiens', code: 'FR' },
              { name: 'Arras', code: 'FR' },
              { name: 'Saint-Malo', code: 'FR' },
              { name: 'Avignon', code: 'FR' },
              { name: 'Saint-Étienne', code: 'FR' },
              { name: 'Vienne', code: 'FR' },
              { name: 'Arcachon', code: 'FR' },
              { name: 'Libourne', code: 'FR' },
              { name: 'Menton', code: 'FR' },
              { name: 'Valenciennes', code: 'FR' },
              { name: 'Douai', code: 'FR' },
              { name: 'Thionville', code: 'FR' },
              { name: 'Quimper', code: 'FR' },
              { name: 'Carcassonne', code: 'FR' },
              { name: 'Annecy', code: 'FR' },
              { name: 'Dax', code: 'FR' },
              { name: 'Saint-Tropez', code: 'FR' },
              { name: 'Lens', code: 'FR' },
              { name: 'Saint-Brieuc', code: 'FR' }
            ],
            Tunisie: [
              { name: 'Tunis', code: 'TN' },
              { name: 'Sfax', code: 'TN' },
              { name: 'Sousse', code: 'TN' },
              { name: 'Bizerte', code: 'TN' },
              { name: 'Gabès', code: 'TN' },
              { name: 'Ariana', code: 'TN' },
              { name: 'Gafsa', code: 'TN' },
              { name: 'Monastir', code: 'TN' },
              { name: 'Ben Arous', code: 'TN' },
              { name: 'Kasserine', code: 'TN' },
              { name: 'Hammamet', code: 'TN' },
              { name: 'Nabeul', code: 'TN' },
              { name: 'Djerba', code: 'TN' },
              { name: 'Médenine', code: 'TN' },
              { name: 'Tataouine', code: 'TN' },
              { name: 'Tozeur', code: 'TN' },
              { name: 'Kébili', code: 'TN' },
              { name: 'Jendouba', code: 'TN' },
              { name: 'Le Kef', code: 'TN' },
              { name: 'Mahdia', code: 'TN' },
              { name: 'Siliana', code: 'TN' },
              { name: 'Manouba', code: 'TN' },
              { name: 'Beja', code: 'TN' },
              { name: 'Kairouan', code: 'TN' },
              { name: 'Zarzis', code: 'TN' },
              { name: 'El Jem', code: 'TN' },
              { name: 'Tabarka', code: 'TN' },
              { name: 'Nefta', code: 'TN' },
              { name: 'Sidi Bouzid', code: 'TN' },
              { name: 'Kelibia', code: 'TN' }
            ],
            Algerie: [
              { name: 'Alger', code: 'DZ' },
              { name: 'Oran', code: 'DZ' },
              { name: 'Constantine', code: 'DZ' },
              { name: 'Annaba', code: 'DZ' },
              { name: 'Blida', code: 'DZ' },
              { name: 'Boumerdès', code: 'DZ' },
              { name: 'Batna', code: 'DZ' },
              { name: 'Tlemcen', code: 'DZ' },
              { name: 'Sétif', code: 'DZ' },
              { name: 'Béjaïa', code: 'DZ' },
              { name: 'Béchar', code: 'DZ' },
              { name: 'Skikda', code: 'DZ' },
              { name: 'Mostaganem', code: 'DZ' },
              { name: 'Tamanrasset', code: 'DZ' },
              { name: 'Ouargla', code: 'DZ' },
              { name: 'Djelfa', code: 'DZ' },
              { name: 'Tizi Ouzou', code: 'DZ' },
              { name: 'Chlef', code: 'DZ' },
              { name: 'Medea', code: 'DZ' },
              { name: 'El Oued', code: 'DZ' },
              { name: 'Ghardaïa', code: 'DZ' },
              { name: 'Laghouat', code: 'DZ' },
              { name: 'Biskra', code: 'DZ' },
              { name: 'Tiaret', code: 'DZ' },
              { name: 'Relizane', code: 'DZ' },
              { name: 'Saïda', code: 'DZ' },
              { name: 'Jijel', code: 'DZ' },
              { name: 'Mascara', code: 'DZ' },
              { name: 'Khenchela', code: 'DZ' },
              { name: 'Tébessa', code: 'DZ' },
              { name: 'El Tarf', code: 'DZ' },
              { name: 'Aïn Defla', code: 'DZ' }
            ],
            Maroc: [
              { name: 'Casablanca', code: 'MA' },
              { name: 'Marrakech', code: 'MA' },
              { name: 'Rabat', code: 'MA' },
              { name: 'Fès', code: 'MA' },
              { name: 'Tangier', code: 'MA' },
              { name: 'Salé', code: 'MA' },
              { name: 'Meknes', code: 'MA' },
              { name: 'Oujda', code: 'MA' },
              { name: 'Agadir', code: 'MA' },
              { name: 'Kenitra', code: 'MA' },
              { name: 'Tetouan', code: 'MA' },
              { name: 'Asilah', code: 'MA' },
              { name: 'Chefchaouen', code: 'MA' },
              { name: 'Essaouira', code: 'MA' },
              { name: 'El Jadida', code: 'MA' },
              { name: 'Khouribga', code: 'MA' },
              { name: 'Beni Mellal', code: 'MA' },
              { name: 'Nador', code: 'MA' },
              { name: 'Safi', code: 'MA' },
              { name: 'Larache', code: 'MA' },
              { name: 'Ksar el-Kebir', code: 'MA' },
              { name: 'Ouarzazate', code: 'MA' },
              { name: 'Zagora', code: 'MA' },
              { name: 'Errachidia', code: 'MA' }
            ]
          }
    };